### ISSUE TITLE
OpenAPI Descriptionを整理したい

### ISSUE THREAD

**Issue by ynm3n** [light-planck/nemmy#159]
今あるものを良くしてから新しいAPIを追加していくほうが良さそうなので、先に細かいところを整理しようかと思います

- [x] 命名をなんとかしたい
  - [x] 複数形、単数形の使い分け
  - [x] 先頭大文字、先頭小文字の使い分け
- [x] ~~parametersをまとめて書きたい(Path Item Objectのフィールドとして書く)~~
- [x] 正常系以外のレスポンスも書きたい
- [x] ~~Redoc~~Scalarを試してSwagger UIと比較したい

**Comment by ynm3n** [comment]
```
paths:
  /users/{username}/subjects:
  /users/{username}/subjects/{subjectId}:
```

`/users/{username}/subjects`の方は`username`必要だけど、`/users/{username}/subjects/{subjectId}`は`username`不要かもな〜と思った
でも後者で`username`を指定しなくていいようなパスってどんな感じがいいかな

**Comment by ynm3n** [comment]
いや、`/users/{username}/subjects/{subjectId}`に`username`が含まれてても別に困らないか

**Comment by ynm3n** [comment]
[Scalar](https://github.com/scalar/scalar)を試したところ、Path Item Objectのフィールド`parameters`(つまり、まとめて書いたparameters)をしっかりと読み取ってくれた。
Scalarに移行することも考えたが、Scalarは`$ref`を使った外部ファイル参照に対応してないようだった。

そのため、以下の方針(従来のものと変わらない)を維持する
- Swagger UIを使い続ける
- Swagger UIではPath Item Objectのparametersを読めないので、parametersはOperation Objectのフィールドに個別に書く

**Comment by ynm3n** [comment]
https://github.com/light-planck/nemmy/blob/main/swagger/public/subjects/paths.yaml#L17
ここ、200なら「成功」、404なら「〇〇が見つからない」、とかがいいかも([Petstore](https://petstore3.swagger.io/#/pet/updatePet)に寄せる場合)

**Comment by light-planck** [comment]
ですね！

**Comment by ynm3n** [comment]
あざます！自分がやりますね〜🙂‍↕️

**Comment by light-planck** [comment]
あざます🙏

**Comment by ynm3n** [comment]
エラーレスポンスで使うスキーマは[RFC 9457 Problem Details](https://www.rfc-editor.org/rfc/rfc9457)を参考に作成することになった

**Comment by ynm3n** [comment]
実際のレスポンスに含まれるメッセージは日本語にするか、英語にするか

現在のところ、OpenAPI Descriptionのsummaryフィールドやdescriptionフィールドは日本語で書いているのでそれに合わせても良い
英語だと良く使われる表現(Not Found や Bad Request など)で書けるから英語のほうが楽という説もあり、こちらでもいい

**Comment by ynm3n** [comment]
<img width="875" src="https://github.com/light-planck/nemmy/assets/43065779/3975dee1-bed8-48e3-ace4-6ad816c7f1b4">
日本語と英語の混在、現状はこんな感じ

**Comment by ynm3n** [comment]
作業が一通り終わったのでクローズします🫡
