### ISSUE TITLE
api: open apiファイルの分割

### ISSUE THREAD

**Issue by light-planck** [light-planck/nemmy#16]

**Comment by ynm3n** [comment]
OpenAPI定義ファイルのディレクトリ分け方法について

以下のうちどっちの分け方が好きですか？(第3の選択肢があったらぜひ書いてください👀)
- 「pathだけをまとめたディレクトリ」「schemaだけをまとめたディレクトリ」…
- 「subject関連の定義(pathやschema等)をまとめたディレクトリ」「user関連の定義だけをまとめたディレクトリ」…

自分的には、同じものを扱うpathとschemaは関連性が高くなる(と思う)ので、後者の方がそれらを近くに配置できるのでまとまり感が出るかなーと思ってます！

**Comment by light-planck** [comment]
後者の設計、package by featureみたいで面白そうですね！
私も後者で良いと思います！
