### ISSUE TITLE
ルールを決める

### ISSUE THREAD

**Issue by light-planck** [light-planck/nemmy#23]
- [ ] コミットメッセージ
- [ ] ブランチ名
- [ ] PR
  - [ ] レビュー
  - [ ] コメント

**Comment by ynm3n** [comment]
この前ちょっと出てましたが、イシューとプルリクエストの使い分け、はっきりさせます？
(プルリクはレビュー依頼のためだけに使う、タスク管理はイシューでやる、など。このルールじゃなくてもいい)

**Comment by light-planck** [comment]
すみません、イシューとプルリクエストの使い分けって何か話し合いましたっけ・・・？

1. 何らかの変更のissueを出す（バグや新機能）
2. コードを変更してprを出す
3. prにissueを紐づける

という使い方を想定しています！

**Comment by ynm3n** [comment]
らいとさんのプルリクページのチェックボックスかっこいい(ynm)
(略)
あれissueのほうに書くべきなのかprに書くべきなのかあまり分からずです(らいとさん)

といったやり取りが前にDiscordであったので、それのことでした！
使い方把握です！👍👍ありがとうございます！

**Comment by light-planck** [comment]
あ、そういうことでした、理解しました！ありがとうございます！

**Comment by light-planck** [comment]
ディスカッションの方でやるのでいったんクローズします！
