### ISSUE TITLE
Biomeを導入する

### ISSUE THREAD

**Issue by light-planck** [light-planck/nemmy#60]
- [ ] prettierを剥がす
- [ ] eslintを剥がす
- [ ] biomeを導入する
- [ ] lefthookの設定しなおす
  - ignoreしているファイル以外はbiomeが対応しているファイル形式はすべてフォーマットしたい(import sortもしたい)
- [ ] ciを設定しなおす（ドキュメントにレシピが載ってます）
  - frontend-ciで、..., biome ci,  buildの順番で行う

**Comment by ynm3n** [comment]
BiomeではNext.jsの公式linterが使えない 等の理由により、一度クローズします。
